name: KostbyNanda
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_fonts: ^4.0.0
  url_launcher: ^6.1.10
  http: ^1.2.2
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon_logooo.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/icon_logooo.jpg
     - assets/logo.png
     - assets/splash_image.png
     - assets/city1.png
     - assets/city2.png
     - assets/city3.png
     - assets/city4.png
     - assets/city5.png
     - assets/icon_star.png
     - assets/space1.png
     - assets/space2.png
     - assets/space3.png
     - assets/space4.png
     - assets/space5.png
     - assets/space6.png
     - assets/tips1.png
     - assets/tips2.png
     - assets/icon_home.png
     - assets/icon_email.png
     - assets/icon_card.png
     - assets/icon_love.png
     - assets/btn_back.png
     - assets/btn_wishlist.png
     - assets/btn_map.png
     - assets/btn_map.png
     - assets/icon_bedroom.png
     - assets/icon_kitchen.png
     - assets/icon_cupboard.png
     - assets/photo1.jpg
     - assets/photo2.jpg
     - assets/photo3.jpg
     - assets/icon_table.png
     - assets/icon_bathroom.png
     - assets/icon_wifi.png
     - assets/icon_ac.png
     - assets/icon_fan.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
